project:
  type: website
  output-dir: docs

website:
  title: "Yukun Jiao"
  navbar:
    left:
      - href: index.qmd
        text: Home
      # - href: project.qmd
      #   text: project
      # - href: about.qmd
      #   text: About me
  page-footer:
    center: "© 2025 Yukun Jiao · Built with [Quarto](https://quarto.org/) and [GitHub Pages](https://pages.github.com/)"



format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: source

