project:
  type: website
  output-dir: docs

website:
  title: "Yukun Jiao"
  navbar:
    left:
      - href: index.qmd
        text: Home
      # - href: project.qmd
      #   text: project
      # - href: about.qmd
      #   text: About me


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: source

